apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-portfolio
spec:
  replicas: 3
  selector:
    matchLabels:
      app: portfolio
  template:
    metadata:
      labels:
        app: portfolio
    spec:
      containers:
        - name: portfolio
          image: vijaymachine12/portfolio:latest
